# Generated by Django 3.2.5 on 2021-07-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('question_number', models.IntegerField()),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Question List',
                'verbose_name_plural': 'Question List',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tests',
                'verbose_name_plural': 'Tests',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.question')),
                ('test', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='polls.test')),
            ],
            options={
                'verbose_name': 'Test questions',
                'verbose_name_plural': 'Test questions',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(through='polls.TestQuestions', to='polls.Question'),
        ),
    ]
