# Generated by Django 3.2.5 on 2021-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210722_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='question_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
