# Generated by Django 3.2.5 on 2021-07-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_testquestions_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='runner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
