# Generated by Django 3.2.5 on 2021-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_testquestions_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='testquestions',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='runner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
