# Generated by Django 3.2.5 on 2021-08-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210801_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_res', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_res', to='polls.testquestions')),
            ],
        ),
    ]
