# Generated by Django 3.2.5 on 2021-08-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210804_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Question List',
                'verbose_name_plural': 'Question List',
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
                ('question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.question')),
                ('test', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='polls.test')),
            ],
            options={
                'verbose_name': 'Test questions',
                'verbose_name_plural': 'Test questions',
                'ordering': ['-question_number'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(through='polls.TestQuestions', to='polls.Question'),
        ),
    ]
