# Generated by Django 3.2.5 on 2021-08-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_testrun_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='questions',
        ),
        migrations.CreateModel(
            name='AnsweredTestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
                ('question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='polls.question')),
                ('test', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_test', to='polls.testrun')),
            ],
            options={
                'verbose_name': 'Test questions',
                'verbose_name_plural': 'Test questions',
                'ordering': ['-question_number'],
            },
        ),
        migrations.AddField(
            model_name='testrun',
            name='questions',
            field=models.ManyToManyField(through='polls.AnsweredTestQuestions', to='polls.Question'),
        ),
    ]
