# Generated by Django 3.2.5 on 2021-08-04 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210805_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeredtestquestions',
            options={'verbose_name': 'Test answer', 'verbose_name_plural': 'Test answers'},
        ),
        migrations.AddField(
            model_name='testrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
