# Generated by Django 3.2.5 on 2021-08-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210805_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='questions',
            field=models.ManyToManyField(related_name='question_list', through='polls.AnsweredTestQuestions', to='polls.Question'),
        ),
    ]
