# Generated by Django 3.2.5 on 2021-08-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_testrun_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='questions',
            field=models.ManyToManyField(through='polls.AnsweredTestQuestions', to='polls.Question'),
        ),
    ]
