# Generated by Django 3.2.5 on 2021-08-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_testrun_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='count_of_questions',
            field=models.IntegerField(null=True),
        ),
    ]
