# Generated by Django 3.2.4 on 2021-08-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_testrun_count_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='testrun',
            name='count_of_created_questions',
            field=models.IntegerField(null=True),
        ),
    ]
