# Generated by Django 3.2.4 on 2021-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20210811_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='runner',
        ),
        migrations.AddField(
            model_name='test',
            name='count_of_runs',
            field=models.IntegerField(null=True),
        ),
    ]
