# Generated by Django 3.2.4 on 2021-08-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20210811_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['created_at'], 'verbose_name': 'Tests', 'verbose_name_plural': 'Tests'},
        ),
    ]
