# Generated by Django 3.2.4 on 2021-08-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_test_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestions',
            options={'ordering': ['question_number'], 'verbose_name': 'Test questions', 'verbose_name_plural': 'Test questions'},
        ),
    ]
