# Generated by Django 3.2.4 on 2021-08-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_testquestions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='count_of_runs',
            field=models.IntegerField(default=0),
        ),
    ]
