# Generated by Django 3.2.6 on 2021-08-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_test_count_of_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestions',
            name='answer',
        ),
    ]
